import * as THREE from 'three';

export class RunnerEffects{
 constructor(scene){this.root=new THREE.Group();scene.add(this.root);this.limit=640;this.items=Array.from({length:this.limit},()=>({life:0}));this.cursor=0;this.position=new Float32Array(this.limit*3);this.color=new Float32Array(this.limit*3);this.alpha=new Float32Array(this.limit);this.size=new Float32Array(this.limit);const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(this.position,3).setUsage(THREE.DynamicDrawUsage));g.setAttribute('tint',new THREE.BufferAttribute(this.color,3).setUsage(THREE.DynamicDrawUsage));g.setAttribute('alpha',new THREE.BufferAttribute(this.alpha,1).setUsage(THREE.DynamicDrawUsage));g.setAttribute('size',new THREE.BufferAttribute(this.size,1).setUsage(THREE.DynamicDrawUsage));
 const m=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,vertexShader:'attribute vec3 tint; attribute float alpha; attribute float size; varying vec3 vTint; varying float vAlpha; void main(){vTint=tint;vAlpha=alpha;vec4 p=modelViewMatrix*vec4(position,1.0);gl_PointSize=clamp(size*420.0/max(1.0,-p.z),0.0,36.0);gl_Position=projectionMatrix*p;}',fragmentShader:'varying vec3 vTint; varying float vAlpha; void main(){float d=length(gl_PointCoord-vec2(.5));if(d>.5)discard;float a=pow(1.0-d*2.0,1.5)*vAlpha;gl_FragColor=vec4(vTint,a);}' });this.points=new THREE.Points(g,m);this.points.frustumCulled=false;this.root.add(this.points);
 this.rings=Array.from({length:8},()=>{const o=new THREE.Mesh(new THREE.RingGeometry(.8,1,48),new THREE.MeshBasicMaterial({color:0x91ffde,transparent:true,opacity:0,side:THREE.DoubleSide,depthWrite:false,blending:THREE.AdditiveBlending}));o.rotation.x=-Math.PI/2;o.visible=false;this.root.add(o);return o;});this.ringCursor=0;
 this.streakPositions=new Float32Array(32*6);const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.BufferAttribute(this.streakPositions,3));this.streaks=new THREE.LineSegments(sg,new THREE.LineBasicMaterial({color:0xbcefff,transparent:true,opacity:.13,depthWrite:false,blending:THREE.AdditiveBlending}));this.streaks.frustumCulled=false;this.root.add(this.streaks);this.streakData=Array.from({length:32},()=>({x:(Math.random()>.5?1:-1)*(4+Math.random()*8),y:1+Math.random()*8,z:-Math.random()*100}));
 this.shake=0;this.kick=0;this.kickVelocity=0;this.boost=0;this.flash=0;this.flashColor='70,220,240';this.accumulator=0;this.ambientAccumulator=0;this.lastTime=0;
 }
 reset(){for(const p of this.items)p.life=0;this.alpha.fill(0);this.points.geometry.attributes.alpha.needsUpdate=true;for(const r of this.rings)r.visible=false;this.shake=this.kick=this.kickVelocity=this.boost=this.flash=0;}
 spawn(x,y,z,vx,vy,vz,color,size=.22,life=.65,gravity=4){const i=this.cursor++%this.limit,p=this.items[i];Object.assign(p,{x,y,z,vx,vy,vz,life,max:life,gravity});this.color.set(color,i*3);this.size[i]=size;}
 burst(x,y,z,count,color,speed=3,gravity=5){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,r=.3+Math.random()*speed;this.spawn(x,y,z,Math.cos(a)*r,Math.random()*speed,Math.sin(a)*r,color,.15+Math.random()*.23,.4+Math.random()*.6,gravity);}}
 ring(x,z,color){const o=this.rings[this.ringCursor++%this.rings.length];o.position.set(x,.035,z);o.scale.setScalar(.2);o.material.color.set(color);o.material.opacity=.65;o.visible=true;o.userData.life=.45;}
 event(type,state,reduced=false){const x=(state?.x||0)*2.2,y=state?.y||0,n=reduced?.3:1;
 if(type==='jump'){this.burst(x,.2,0,24*n,[.2,.8,1],3,2);this.ring(x,0,0x80deff);this.kickVelocity-=reduced?0:1.4;this.boost=.7;}
 if(type==='wrap'){this.burst(x,1+y,0,48*n,[.7,.4,1],4,0);this.ring(x,0,0xc69cff);this.flash=reduced?.05:.18;this.flashColor='165,100,255';}
 if(type==='land'){this.burst(x,.06,0,32*n,[.9,.59,.3],3.2,6);this.ring(x,0,0xf9bb72);this.kickVelocity+=reduced?0:3.5;this.shake=Math.max(this.shake,reduced?0:.055);}
 if(type==='coin'){this.burst(x,1.1+y,-.1,26*n,[1,.68,.16],3.6,2);this.flash=reduced?.03:.1;this.flashColor='255,190,58';}
 if(type==='combo'){this.burst(x,1.2+y,0,48*n,[.5,1,.7],5,1);this.boost=1;this.flash=.2;this.flashColor='68,230,204';}
 if(type==='hit'){this.burst(x,1+y,0,70*n,[1,.3,.06],6,8);this.shake=reduced?0:.23;this.kickVelocity+=reduced?0:5;this.flash=reduced?.15:.7;this.flashColor='255,83,43';this.boost=0;}
 if(type==='launch'){this.burst(x,.3,0,50*n,[.2,.85,1],6,2);this.boost=1.2;this.ring(x,0,0x73ffe5);}
 if(type==='won'){for(let i=0;i<5;i++)this.burst((i-2)*1.8,3+Math.random()*3,-3,50*n,i%2?[1,.68,.2]:[.3,1,.85],6,2);this.boost=1.4;}
 }
 update(dt,state,time,theme,reduced){const active=!!state;this.root.visible=active;if(!active)return;const paused=state.status==='paused',step=paused?0:dt,speed=state.status==='running'&&state.hop?state.mission.speed:0,x=state.x*2.2;this.shake*=Math.exp(-step*9);this.boost*=Math.exp(-step*3);this.flash*=Math.exp(-step*7);this.kickVelocity+=(-this.kick*130-this.kickVelocity*15)*step;this.kick+=this.kickVelocity*step;
 if(speed){this.accumulator+=step;while(this.accumulator>.055){this.accumulator-=.055;if(!reduced){const airborne=state.y>0;this.spawn(x+(Math.random()-.5)*.5,state.y+.08,.25,(Math.random()-.5)*.7,.4,2+Math.random()*3,airborne?[.2,.7,1]:[.6,.35,.16],airborne?.22:.16,.35,1);}}
 this.ambientAccumulator+=step;while(this.ambientAccumulator>.05){this.ambientAccumulator-=.05;const color=theme==='lava'?[1,.3,.03]:theme==='ice'?[.5,.9,1]:[.6,.42,.25];this.spawn((Math.random()-.5)*20,Math.random()*7,-20-Math.random()*75,-.4,theme==='lava'?.6:-.15,speed*.5,color,.12+Math.random()*.12,3,0);}}
 for(let i=0;i<this.limit;i++){const p=this.items[i];if(p.life>0){p.life-=step;p.x+=p.vx*step;p.y+=p.vy*step;p.z+=p.vz*step;p.vy-=p.gravity*step;this.position.set([p.x,p.y,p.z],i*3);this.alpha[i]=Math.max(0,p.life/p.max);}else this.alpha[i]=0;}for(const attr of Object.values(this.points.geometry.attributes))attr.needsUpdate=true;
 for(const r of this.rings)if(r.visible){r.userData.life-=step;r.scale.addScalar(step*5);r.material.opacity=Math.max(0,r.userData.life*1.3);r.position.z+=speed*step*.15;if(r.userData.life<=0)r.visible=false;}
 this.streaks.visible=!!speed&&!reduced;this.streaks.material.opacity=.04+this.boost*.15;for(let i=0;i<32;i++){const s=this.streakData[i];s.z+=step*speed*1.7;if(s.z>12)s.z=-110;this.streakPositions.set([s.x,s.y,s.z,s.x,s.y,s.z-1.4-this.boost*3],i*6);}this.streaks.geometry.attributes.position.needsUpdate=true;
 const overlay=document.getElementById('screen-fx');if(overlay){overlay.style.opacity=String(this.flash);overlay.style.background=`radial-gradient(ellipse at center,transparent 38%,rgba(${this.flashColor},.72))`;}
 }
}
