/* Original game implementation. Official Dogelon artwork: see assets/CREDITS.md. */
(()=>{'use strict';
const $=id=>document.getElementById(id),C=MarsCore,canvas=$('scene');
let renderer;
try{renderer=new MarsRenderer(canvas);}catch(error){$('loading').innerHTML='3D COULD NOT START<span>Enable WebGL / hardware acceleration in your browser and reload.</span>';console.error(error);return;}
let W=1280,H=720,selected=0,state=null,screen='menu',clock=0,last=0,save=C.cleanSave(null),audio=null,damageNoise=null,sound=true,modal=null,toastUntil=0,returnFocus=null,hitStop=0,comboCount=0,comboUntil=0,musicTarget='menu';
const music={menu:new Audio('assets/Warm Cosmic Arpeggios.mp3'),game:new Audio('assets/Coin Collectors Guide.mp3')},musicVolume={menu:.3,game:.24},coinSound=new Audio('assets/coin-recived.mp3');
for(const track of Object.values(music)){track.loop=true;track.preload='auto';track.volume=0;}coinSound.preload='auto';coinSound.volume=.72;
try{save=C.cleanSave(JSON.parse(localStorage.getItem('dogelon-mars-puzzle-v2')));}catch{}
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
try{const motion=localStorage.getItem('mars-calm-camera');if(motion!==null)reduced=motion==='true';}catch{}
function resize(){W=innerWidth;H=innerHeight;renderer.resize(W,H);}
addEventListener('resize',resize);resize();
function show(id,visible){$(id).classList.toggle('hidden',!visible);}
function beep(freq=500,duration=.1,type='sine',volume=.035){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.6,audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function setMusic(target){musicTarget=target;if(sound&&!document.hidden)music[target].play().catch(()=>{});}
function updateAudio(dt){for(const [name,track] of Object.entries(music)){const target=sound&&!document.hidden&&name===musicTarget?musicVolume[name]:0;if(target&&track.paused)track.play().catch(()=>{});track.volume=Math.max(0,Math.min(1,track.volume+(target-track.volume)*(1-Math.exp(-3.5*dt))));if(!target&&track.volume<.002&&!track.paused){track.volume=0;track.pause();}}}
function collectSound(){if(!sound)return;coinSound.currentTime=0;coinSound.play().catch(()=>{});}
function damageSound(){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const now=audio.currentTime,o=audio.createOscillator(),og=audio.createGain();o.type='sawtooth';o.frequency.setValueAtTime(145,now);o.frequency.exponentialRampToValueAtTime(42,now+.24);og.gain.setValueAtTime(.09,now);og.gain.exponentialRampToValueAtTime(.001,now+.25);o.connect(og);og.connect(audio.destination);o.start(now);o.stop(now+.26);if(!damageNoise){damageNoise=audio.createBuffer(1,Math.floor(audio.sampleRate*.18),audio.sampleRate);const data=damageNoise.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);}const noise=audio.createBufferSource(),filter=audio.createBiquadFilter(),ng=audio.createGain();noise.buffer=damageNoise;filter.type='lowpass';filter.frequency.setValueAtTime(950,now);filter.frequency.exponentialRampToValueAtTime(180,now+.18);ng.gain.setValueAtTime(.075,now);ng.gain.exponentialRampToValueAtTime(.001,now+.18);noise.connect(filter);filter.connect(ng);ng.connect(audio.destination);noise.start(now);}catch{}}
const unlockMusic=()=>{if(sound)setMusic(screen==='menu'?'menu':'game');};document.addEventListener('pointerdown',unlockMusic,{once:true,capture:true});document.addEventListener('keydown',unlockMusic,{once:true,capture:true});
function selectPlanet(index){if(screen!=='menu'||modal||index<0||index>=C.missions.length)return;selected=index;refreshMenu();beep(340,.06);}
document.addEventListener('mars-select-planet',e=>selectPlanet(e.detail));
function refreshMenu(){const el=$('missions');el.replaceChildren();C.missions.forEach((m,i)=>{const b=document.createElement('button');b.className='mission'+(selected===i?' selected':'');b.setAttribute('aria-label',`${m.name} — ${save.stars[i]} stars`);b.setAttribute('aria-pressed',String(selected===i));b.addEventListener('pointerdown',e=>e.stopPropagation());b.addEventListener('pointerup',e=>e.stopPropagation());b.onclick=()=>selectPlanet(i);el.append(b);});}
function menu(){screen='menu';setMusic('menu');state=null;modal=null;hitStop=0;comboCount=0;renderer.fx.reset();show('menu',true);for(const id of ['hud','ready','game-tip','touch-controls','overlay','pause','toast','combo'])show(id,false);refreshMenu();$('launch').focus({preventScroll:true});}
function launch(){screen='game';setMusic('game');state=C.create(selected,Math.floor(Math.random()*1e9));hitStop=0;comboCount=0;show('combo',false);show('menu',false);show('hud',true);show('ready',true);show('touch-controls',false);show('game-tip',true);show('pause',false);show('overlay',false);$('ready').querySelector('span').textContent=`${state.mission.name.toUpperCase()} · MISSION ${String(selected+1).padStart(2,'0')}`;$('ready').querySelector('p').textContent='↖ Left or right ↗ · One leap per move';updateHud();$('begin').focus({preventScroll:true});}
function begin(){if(!state||state.status!=='ready')return;state.status='running';renderer.fx.event('launch',state,reduced);show('ready',false);show('touch-controls',true);show('pause',true);$('begin').blur();beep(480,.2);toast('CHOOSE ↖ OR ↗ · EDGES WRAP AROUND',3);}
function toast(text,duration=1.5){$('toast').textContent=text;show('toast',true);toastUntil=clock+duration;}
function updateHud(){if(!state)return;$('hud-sector').textContent=`${String(selected+1).padStart(2,'0')} — ${state.mission.name.toUpperCase()}`;$('distance').innerHTML=`${state.row}<span> / ${state.mission.rows} ROWS</span>`;$('timer').textContent=state.jumpCount;$('coins').textContent=state.coins;$('lives').textContent='◆ '.repeat(state.lives)+'◇ '.repeat(3-state.lives);$('lives').setAttribute('aria-label',`${state.lives} shields remaining`);$('progress').style.width=`${state.distance/state.mission.length*100}%`;}
function dialog(title,eyebrow,content,primary,action,secondary){returnFocus=document.activeElement;show('overlay',true);$('overlay-title').textContent=title;$('overlay-eyebrow').textContent=eyebrow;$('overlay-content').innerHTML=content;$('overlay-primary').innerHTML=primary+' <span>↗</span>';$('overlay-primary').onclick=action;show('overlay-secondary',!!secondary);$('overlay-secondary').onclick=secondary||null;$('overlay-primary').focus({preventScroll:true});}
function closeDialog(){show('overlay',false);modal=null;if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});}
function pause(){if(!state||!['running','paused'].includes(state.status))return;if(state.status==='paused'){state.status='running';closeDialog();return;}state.status='paused';modal='pause';dialog('Take a breather.','MISSION PAUSED','<p>Mars will still be here.<br>Your run is saved right where you left it.</p>','KEEP HOPPING',pause,menu);}
function help(){if(modal)return;const resume=state?.status==='running';if(resume)state.status='paused';modal='help';dialog('Think. Then leap.','HOW TO HOP','<p>No automatic movement. Take as long as you need to choose your next tile.</p><div class="help-row"><span>Jump forward-left</span><span><kbd>←</kbd> / A</span></div><div class="help-row"><span>Jump forward-right</span><span><kbd>→</kbd> / D</span></div><div class="help-row"><span>Pause</span><kbd>P / ESC</kbd></div><p>Jumping past the left edge lands on the right side of the next row, and vice versa. Land on a clear tile: rocks, spikes and gaps cost a shield and return you to your previous tile. Three mistakes end the attempt.</p><p>Tap a side or use the two jump buttons. Collect Dogelon coins along the way. Finish for ★, collect 50% for ★★, collect 75% without mistakes for ★★★.</p>','GOT IT',()=>{if(resume)state.status='running';closeDialog();});}
function finish(won){show('pause',false);show('touch-controls',false);show('game-tip',false);show('toast',false);modal='result';const rating=C.rating(state);if(won){save.stars[selected]=Math.max(save.stars[selected],rating);save=C.cleanSave(save);try{localStorage.setItem('dogelon-mars-puzzle-v2',JSON.stringify(save));}catch{}beep(880,.4);}
 const content=(won?`<div class="result-stars">${'★'.repeat(rating)}${'☆'.repeat(3-rating)}</div>`:'<p>A little cosmic turbulence. Pick yourself up and give Mars another shot.</p>')+`<div class="result-stats"><div><strong>${state.coins}</strong><small>COINS</small></div><div><strong>${state.row} / ${state.mission.rows}</strong><small>ROWS</small></div><div><strong>${state.jumpCount}</strong><small>MOVES</small></div></div>`+(won&&selected===5?'<p>You made it home! Replay missions to collect all 18 stars.</p>':'');
 dialog(won?(selected===5?'Welcome home.':'One giant leap.'):'Back on your paws.',won?'MISSION COMPLETE':'SIGNAL LOST',content,won&&selected<5?'NEXT MISSION':'HOP AGAIN',()=>{if(won&&selected<5)selected++;modal=null;launch();},menu);
}
$('launch').onclick=launch;$('begin').onclick=begin;$('home').onclick=()=>{if(state?.status==='running'){pause();}else menu();};$('pause').onclick=pause;$('help').onclick=help;$('controls-link').onclick=help;
function soundUI(){$('sound').setAttribute('aria-label',sound?'Mute sound':'Enable sound');$('sound').querySelector('span').style.display=sound?'none':'';}soundUI();
$('sound').onclick=()=>{sound=!sound;soundUI();if(sound){setMusic(screen==='menu'?'menu':'game');beep(600,.08);}else for(const track of Object.values(music)){track.volume=0;track.pause();}};
function motionUI(){$('motion').setAttribute('aria-pressed',String(reduced));$('motion').setAttribute('aria-label',reduced?'Enable camera motion':'Reduce camera motion');}motionUI();
$('motion').onclick=()=>{reduced=!reduced;renderer.fx.shake=renderer.fx.kick=renderer.fx.kickVelocity=0;try{localStorage.setItem('mars-calm-camera',String(reduced));}catch{}motionUI();};
function move(dir){if(modal)return;if(state&&C.move(state,dir)){beep(390,.13,'triangle');renderer.fx.event('jump',state,reduced);}}
$('left').onclick=()=>move(-1);$('right').onclick=()=>move(1);
document.addEventListener('keydown',e=>{if(e.code==='Tab'&&!$('overlay').classList.contains('hidden')){const buttons=[...$('overlay').querySelectorAll('button:not(.hidden)')];if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){e.preventDefault();buttons[0].focus();}return;}if(e.repeat)return;if(['ArrowLeft','ArrowRight','ArrowUp','Space'].includes(e.code)&&screen==='game')e.preventDefault();if(e.code==='Escape'&&modal==='help'){$('overlay-primary').click();return;}if(e.code==='KeyP'||e.code==='Escape'){if(modal==='pause'||!modal)pause();return;}if(modal)return;if(state?.status==='ready'&&['Space','Enter','ArrowLeft','ArrowRight','ArrowUp'].includes(e.code)){begin();return;}if(['ArrowLeft','KeyA'].includes(e.code))move(-1);if(['ArrowRight','KeyD'].includes(e.code))move(1);});
let pointer=null;canvas.addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY};});canvas.addEventListener('pointerup',e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;pointer=null;if(state?.status==='ready'){begin();return;}if(Math.abs(dx)>25&&Math.abs(dx)>Math.abs(dy))move(dx>0?1:-1);else if(Math.hypot(dx,dy)<20)move(e.clientX<W/2?-1:1);});canvas.addEventListener('pointercancel',()=>pointer=null);
document.addEventListener('visibilitychange',()=>{if(document.hidden){for(const track of Object.values(music))track.pause();if(state?.status==='running')pause();}else if(sound)setMusic(screen==='menu'?'menu':'game');});
function render(dt){renderer.draw(state,selected,clock,screen,reduced,dt);}
document.addEventListener('mars-renderer-lost',()=>{if(state?.status==='running')pause();toast('3D CONTEXT LOST · RELOAD TO RECOVER',30);});
function frame(t){const dt=Math.min((t-last)/1000||0,.05);last=t;clock+=dt;updateAudio(dt);if(state?.status==='running'){const signals=hitStop>0?[]:C.step(state,dt);hitStop=Math.max(0,hitStop-dt);for(const s of signals){if(s==='coin'){collectSound();renderer.fx.event('coin',state,reduced);comboCount++;if(comboCount%3===0){renderer.fx.event('combo',state,reduced);$('combo').textContent=`COIN STREAK × ${comboCount}`;show('combo',true);comboUntil=clock+1.4;beep(1240,.16,'triangle');}}if(s==='wrap'){renderer.fx.event('wrap',state,reduced);beep(660,.12,'sine');}if(s==='land'){if(!signals.includes('hit'))renderer.landTile(state,reduced);renderer.fx.event('land',state,reduced);beep(85,.075,'triangle',.025);}if(s==='hit'){comboCount=0;show('combo',false);hitStop=reduced?0:.065;damageSound();renderer.fx.event('hit',state,reduced);toast(`${state.lives} SHIELD${state.lives===1?'':'S'} LEFT · TRY THE OTHER DIRECTION`);}if(s==='won'||s==='lost'){if(s==='won')renderer.fx.event('won',state,reduced);finish(s==='won');}}updateHud();}if(clock>toastUntil)show('toast',false);if(clock>comboUntil)show('combo',false);render(dt);requestAnimationFrame(frame);}
renderer.ready.then(()=>{show('loading',false);refreshMenu();setMusic('menu');requestAnimationFrame(frame);}).catch(error=>{console.error(error);$('loading').innerHTML='DOGELON COULD NOT LOAD<span>Check the local model file and reload.</span>';});
})();


