import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

function rng(seed){return()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};}
export function glowTexture(){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d'),g=x.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'#ffffff');g.addColorStop(.13,'#ffffffdc');g.addColorStop(.35,'#ffffff45');g.addColorStop(1,'#ffffff00');x.fillStyle=g;x.fillRect(0,0,128,128);return new THREE.CanvasTexture(c);}
function surface(index){const c=document.createElement('canvas');c.width=512;c.height=256;const x=c.getContext('2d'),r=rng(931+index),palettes=[['#d77846','#964533','#f2b56f'],['#8d94a2','#515767','#c0c9d2'],['#56bfc8','#226b8c','#c4f1e7'],['#c55a3d','#713341','#e29557'],['#574154','#211e35','#ea5728'],['#eb8850','#a64630','#ffc783']];const p=palettes[index];x.fillStyle=p[0];x.fillRect(0,0,512,256);for(let i=0;i<160;i++){x.globalAlpha=.08+r()*.3;x.fillStyle=p[i%3];x.beginPath();x.ellipse(r()*512,r()*256,4+r()*35,2+r()*12,r()*3,0,Math.PI*2);x.fill();}for(let i=0;i<6000;i++){x.globalAlpha=r()*.16;x.fillStyle=i%2?'#fff':'#000';x.fillRect(r()*512,r()*256,1,1);}if(index===2){x.globalAlpha=.55;x.fillStyle='#d5fff0';x.fillRect(0,0,512,23);x.fillRect(0,235,512,21);}if(index===4){x.globalAlpha=.85;x.strokeStyle='#ff7434';x.lineWidth=2;for(let i=0;i<14;i++){x.beginPath();let xx=r()*512,yy=r()*256;x.moveTo(xx,yy);for(let k=0;k<10;k++){xx+=r()*25-10;yy+=r()*18-4;x.lineTo(xx,yy);}x.stroke();}}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}

export class SolarMap{
 constructor(canvas,element){this.canvas=canvas;this.element=element;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x060b1e);this.camera=new THREE.PerspectiveCamera(43,1,.1,600);this.controls=new OrbitControls(this.camera,element);this.controls.enablePan=false;this.controls.enableDamping=true;this.controls.dampingFactor=.075;this.controls.rotateSpeed=.45;this.controls.zoomSpeed=.7;this.controls.minPolarAngle=.32;this.controls.maxPolarAngle=1.32;this.controls.target.set(0,0,0);this.controls.enabled=true;
 this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.projected=new THREE.Vector3();this.draggedUntil=0;this.root=new THREE.Group();this.scene.add(this.root);this.scene.add(new THREE.HemisphereLight(0xcbdcff,0x30446f,1.7));const light=new THREE.PointLight(0xffdda9,55,100,1.3);this.scene.add(light);const key=new THREE.DirectionalLight(0xadcfff,1);key.position.set(0,10,15);this.scene.add(key);
 this.glow=glowTexture();const sun=new THREE.Mesh(new THREE.SphereGeometry(1.48,40,24),new THREE.MeshBasicMaterial({color:0xffd795}));this.root.add(sun);this.sun=sun;const halo=new THREE.Sprite(new THREE.SpriteMaterial({map:this.glow,color:0xffb25b,blending:THREE.AdditiveBlending,depthWrite:false,opacity:.9}));halo.scale.set(11,11,1);this.root.add(halo);this.halo=halo;
 this.planets=[];this.radii=[4.2,5.9,7.3,9.1,10.8,12.6];const angles=[2.2,4.35,5.35,.4,1.48,3.28],sizes=[.78,.64,.88,.77,.91,1.12];
 for(let i=0;i<6;i++){const group=new THREE.Group(),sphere=new THREE.Mesh(new THREE.SphereGeometry(sizes[i],40,24),new THREE.MeshStandardMaterial({map:surface(i),roughness:.8,metalness:.02}));sphere.userData.planetIndex=i;group.add(sphere);sphere.rotation.z=(i-2)*.07;const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(sizes[i]*1.065,32,20),new THREE.MeshBasicMaterial({color:[0xffa771,0x9fbbff,0x72f9f1,0xfa9d7e,0xd78afb,0xffc485][i],transparent:true,opacity:.1,side:THREE.BackSide}));group.add(atmosphere);
 if(i===2||i===4){const ring=new THREE.Mesh(new THREE.RingGeometry(sizes[i]*1.3,sizes[i]*1.85,72),new THREE.MeshBasicMaterial({color:i===2?0x9ce4eb:0xcfacd9,transparent:true,opacity:.3,side:THREE.DoubleSide}));ring.rotation.x=1.18;ring.rotation.y=.25;group.add(ring);}
 const selection=new THREE.Mesh(new THREE.TorusGeometry(sizes[i]*1.35,.025,6,64),new THREE.MeshBasicMaterial({color:0x75ffe0}));selection.rotation.x=-Math.PI/2;group.add(selection);selection.visible=false;
 this.root.add(group);this.planets.push({group,sphere,selection,angle:angles[i],radius:this.radii[i],size:sizes[i]});const vertices=[];for(let j=0;j<=120;j++){const a=j/120*Math.PI*2;vertices.push(Math.cos(a)*this.radii[i],0,Math.sin(a)*this.radii[i]);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));this.root.add(new THREE.Line(g,new THREE.LineBasicMaterial({color:0x6686b0,transparent:true,opacity:.25})));}
 const rand=rng(119),d=new THREE.Object3D(),belt=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,0),new THREE.MeshStandardMaterial({color:0x8797b1,roughness:1}),320);for(let i=0;i<320;i++){const a=rand()*Math.PI*2,r=8+rand()*.42;d.position.set(Math.cos(a)*r,(rand()-.5)*.3,Math.sin(a)*r);d.scale.setScalar(.025+rand()*.065);d.rotation.set(rand()*3,rand()*3,rand()*3);d.updateMatrix();belt.setMatrixAt(i,d.matrix);}this.root.add(belt);this.belt=belt;
 const stars=[];for(let i=0;i<1800;i++){const v=new THREE.Vector3(rand()-.5,rand()-.5,rand()-.5).normalize().multiplyScalar(90+rand()*180);stars.push(v.x,v.y,v.z);}const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.Float32BufferAttribute(stars,3));this.starfield=new THREE.Points(sg,new THREE.PointsMaterial({color:0xb9d7f5,size:.24,transparent:true,opacity:.8}));this.scene.add(this.starfield);
 element.addEventListener('pointerdown',e=>{if(!this.controls.enabled)return;this.down={x:e.clientX,y:e.clientY};});element.addEventListener('pointermove',e=>{if(this.down&&Math.hypot(e.clientX-this.down.x,e.clientY-this.down.y)>7)this.draggedUntil=performance.now()+300;});element.addEventListener('pointerup',e=>{if(!this.controls.enabled)return;if(this.down&&performance.now()>this.draggedUntil){const rect=canvas.getBoundingClientRect();this.pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);const hit=this.ray.intersectObjects(this.planets.map(p=>p.sphere),false)[0];if(hit)document.dispatchEvent(new CustomEvent('mars-select-planet',{detail:hit.object.userData.planetIndex}));}this.down=null;});element.addEventListener('pointercancel',()=>{this.down=null;});
 }
 resize(w,h){this.width=w;this.height=h;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.fitDistance=Math.max(43,32/(w/h));this.controls.minDistance=this.fitDistance*.86;this.controls.maxDistance=this.fitDistance*1.65;this.reset();}
 reset(){const d=this.fitDistance;this.controls.target.set(0,-1.3,0);this.camera.position.set(d*.12,d*.6-1.3,d*.8);this.controls.update();}
 rotate(amount){const offset=this.camera.position.clone().sub(this.controls.target);offset.applyAxisAngle(new THREE.Vector3(0,1,0),amount);this.camera.position.copy(this.controls.target).add(offset);this.controls.update();}
 zoom(factor){const offset=this.camera.position.clone().sub(this.controls.target);offset.setLength(THREE.MathUtils.clamp(offset.length()*factor,this.controls.minDistance,this.controls.maxDistance));this.camera.position.copy(this.controls.target).add(offset);this.controls.update();}
 update(time,index,reduced){this.controls.update();const motion=time*(reduced?.55:1);this.halo.material.opacity=.8+Math.sin(motion*1.4)*.05;this.belt.rotation.y=motion*.022;this.starfield.rotation.y=motion*.012;this.starfield.rotation.z=Math.sin(motion*.04)*.06;this.starfield.material.opacity=.76+Math.sin(motion*.55)*.06;this.root.updateMatrixWorld(true);
 const labels=document.getElementById('missions').children;
 for(let i=0;i<6;i++){const p=this.planets[i],a=p.angle+motion*.065/(1+i*.15);p.group.position.set(Math.cos(a)*p.radius,Math.sin(a*2)*.13,Math.sin(a)*p.radius);p.sphere.rotation.y=motion*(.13+i*.02);p.selection.visible=i===index;p.selection.rotation.z=motion*.4;p.group.scale.lerp(new THREE.Vector3().setScalar(i===index?1.15:1),.1);
 if(labels[i]){this.projected.copy(p.group.position);this.projected.project(this.camera);const x=(this.projected.x*.5+.5)*this.width,y=(-this.projected.y*.5+.5)*this.height;labels[i].style.left=x+'px';labels[i].style.top=y+'px';labels[i].style.zIndex=String(Math.round(100-this.projected.z*40));labels[i].style.visibility=this.projected.z>1||x<5||x>this.width-5||y<100||y>this.height-100?'hidden':'visible';}}
 }
 render(renderer,time,index,reduced){this.update(time,index,reduced);renderer.toneMappingExposure=1;renderer.render(this.scene,this.camera);renderer.toneMappingExposure=1.3;}
}
