const {test}=require('node:test');const assert=require('node:assert/strict');const C=require('../core.js');
function ready(index=0,seed=1){const s=C.create(index,seed);s.status='running';return s;}
function settle(s){const signals=[];for(let i=0;s.hop&&i<100;i++)signals.push(...C.step(s,1/60));assert.equal(s.hop,null);return signals;}
function clear(s){s.events.forEach(e=>e.hazards=[]);return s;}
test('waiting never advances the puzzle or triggers a hazard',()=>{const s=ready(),before=JSON.stringify(s);for(let i=0;i<1000;i++)assert.deepEqual(C.step(s,.05),[]);assert.equal(JSON.stringify(s),before);});
test('one input makes exactly one forward diagonal leap',()=>{for(const dir of [-1,1]){const s=clear(ready());assert.equal(C.move(s,dir),true);assert.equal(C.move(s,-dir),false);const signals=settle(s);assert.equal(s.row,1);assert.equal(s.lane,dir);assert.equal(s.distance,C.ROW);assert.equal(s.y,0);assert.equal(s.jumpCount,1);assert.equal(signals.filter(x=>x==='land').length,1);for(let i=0;i<60;i++)C.step(s,.05);assert.equal(s.row,1);}});
test('both edges wrap to the opposite lane on the next row',()=>{for(const dir of [-1,1]){const s=clear(ready());C.move(s,dir);settle(s);C.move(s,dir);const signals=settle(s);assert.equal(s.row,2);assert.equal(s.lane,-dir);assert.equal(signals.filter(x=>x==='wrap').length,1);}});
test('no forward-only or invalid direction is accepted',()=>{const s=ready();for(const dir of [0,2,-2,undefined,NaN])assert.equal(C.move(s,dir),false);assert.equal(s.hop,null);});
test('pause freezes a leap and resumes the same trajectory',()=>{const s=clear(ready());C.move(s,1);C.step(s,.05);s.status='paused';const before=JSON.stringify(s);C.step(s,.05);assert.equal(JSON.stringify(s),before);assert.equal(C.move(s,-1),false);s.status='running';settle(s);assert.equal(s.row,1);assert.equal(s.lane,1);});
test('hazards resolve only at landing and return to the previous tile',()=>{for(const type of ['rock','gap','spikes']){const s=ready();s.events[0].hazards=[{lane:-1,type}];C.move(s,-1);C.step(s,.05);assert.equal(s.lives,3);const signals=settle(s);assert.ok(signals.includes('hit'));assert.equal(s.lives,2);assert.equal(s.row,0);assert.equal(s.lane,0);assert.equal(s.events[0].checked,false);C.move(s,1);settle(s);assert.equal(s.row,1);}});
test('three mistakes end the attempt, even when consecutive',()=>{const s=ready();s.events[0].hazards=[{lane:1,type:'rock'}];for(let i=0;i<3;i++){C.move(s,1);settle(s);}assert.equal(s.status,'lost');assert.equal(s.lives,0);assert.equal(C.move(s,-1),false);assert.equal(C.rating(s),0);});
test('240 random puzzles are solvable from every reachable safe tile',()=>{for(let index=0;index<6;index++)for(let seed=1;seed<=40;seed++){const s=ready(index,seed);let lanes=new Set([0]);for(const row of s.events){const next=new Set();for(const lane of lanes){const options=[C.wrap(lane-1),C.wrap(lane+1)].filter(l=>!row.hazards.some(h=>h.lane===l));assert.ok(options.length,`dead end: ${index}/${seed}/${row.row}/${lane}`);options.forEach(l=>next.add(l));}lanes=next;}while(s.status==='running'){const e=s.events[s.row];const dir=[-1,1].find(d=>!e.hazards.some(h=>h.lane===C.wrap(s.lane+d)));assert.ok(dir);C.move(s,dir);settle(s);}assert.equal(s.status,'won');assert.equal(s.hits,0);assert.equal(s.row,s.mission.rows);}});
test('generated courses repeat by seed and differ between seeds',()=>{for(let i=0;i<6;i++){assert.deepEqual(C.course(i,12),C.course(i,12));assert.notDeepEqual(C.course(i,12),C.course(i,13));}});
test('collected coins and victory rating reflect landings',()=>{const s=clear(ready());for(const e of s.events)e.coinLane=C.wrap(e.row);while(s.status==='running'){C.move(s,1);settle(s);}assert.equal(s.coins,s.events.length);assert.equal(C.rating(s),3);});
test('stored stars are validated',()=>{assert.deepEqual(C.cleanSave({stars:[-1,9,'bad',2]}),{stars:[0,3,0,2,0,0],unlocked:0});});
test('coins are sparse and every puzzle offers a route that collects them all',()=>{for(let i=0;i<6;i++)for(let seed=0;seed<40;seed++){const s=ready(i,seed),total=C.coinTotal(s);assert.ok(total>=6);assert.ok(total<s.events.length/2);while(s.status==='running'){const e=s.events[s.row],dir=[-1,1].find(d=>C.wrap(s.lane+d)===e.pathLane);assert.ok(dir);C.move(s,dir);settle(s);}assert.equal(C.rating(s),3);assert.equal(s.coins,total);}});
